export default [
    {
        question: "What is the Crypto Cannabis Club?",
        answer: "The Crypto Cannabis Club is the premier hub for crypto enthusiasts and cannabis connoisseurs on the blockchain. Join the club to chill with like-minded individuals in the metaverse and compete in digital cannabis competitions for physical prizes and NFTs. Membership to the Crypto Cannabis Club will confer exclusive real world and on-chain benefits, and is reserved only to the owners of the NFTokers NFT collection."
    },
    {
        question: "What are NFTokers?",
        answer: "NFTokers are a collection of 10,000 unique NFT avatars chilling on the Ethereum blockchain. Owning an NFToker grants you exclusive access to the Crypto Cannabis Club. Each NFToker is algorithmically generated by randomly combining together numerous professionally illustrated properties across 9 categories. NFTokers possess not only badass aesthetics but also hidden attributes that boost their skills in our re-occuring on-chain cannabis grow competition, the Crypto Cannabis Cup."
    },
    {
        question: "What is the Crypto Cannabis Cup?",
        answer: "The Crypto Cannabis Cup is the most prestigious digital cannabis grow competition on the blockchain. Competition winners will receive real world cannabis-related prizes as well as NFTs. Winning these competitions will take a combination of luck and skill. In addition to your NFToker’s hidden attributes, real world cannabis growing and breeding knowledge will factor in so study up to increase your chances of earning the title of the best grower on the blockchain."
    },
    {
        question: "How can I join the Crypto Cannabis Club?",
        answer: "The Crypto Cannabis Cup is the most prestigious digital cannabis grow competition on the blockchain. Competition winners will receive real world cannabis-related prizes as well as NFTs. Winning these competitions will take a combination of luck and skill. In addition to your NFToker’s hidden attributes, real world cannabis growing and breeding knowledge will factor in so study up to increase your chances of earning the title of the best grower on the blockchain."
    },
    {
        question: "Is there Utility?",
        answer: "The Crypto Cannabis Cup is the most prestigious digital cannabis grow competition on the blockchain. Competition winners will receive real world cannabis-related prizes as well as NFTs. Winning these competitions will take a combination of luck and skill. In addition to your NFToker’s hidden attributes, real world cannabis growing and breeding knowledge will factor in so study up to increase your chances of earning the title of the best grower on the blockchain."
    },
    {
        question: "Tell me about Play to Earn within CCC.",
        answer: "The Crypto Cannabis Cup is the most prestigious digital cannabis grow competition on the blockchain. Competition winners will receive real world cannabis-related prizes as well as NFTs. Winning these competitions will take a combination of luck and skill. In addition to your NFToker’s hidden attributes, real world cannabis growing and breeding knowledge will factor in so study up to increase your chances of earning the title of the best grower on the blockchain."
    }
]